### ISSUE TITLE
Exception when trying to view an Emscripten-generated .wasm file

### ISSUE THREAD

**Issue by mihaip** [evmar/weave#1]
I tried this with the build of BasiliskII that I use on system7.app ([BasiliskII.wasm.zip](https://github.com/evmar/weave/files/8598309/BasiliskII.wasm.zip)) and failed with a `RangeError: Invalid DataView length -939333` exception.

It looks like it's happening in a `sourceMappingURL`  custom section, but I have not investigated further.

**Comment by evmar** [comment]
Thanks, I'll look into it!

**Comment by evmar** [comment]
I pushed a new demo JS bundle but github pages takes a while to update.

Here's some things I noticed in your bundle:
- emscripten, built with function names included but not debug info, maybe `-g2` or something?
- I like how `htons` and `ntohs` are both exported but just point at the same function, never really thought about that before
- the memory section seems to request exactly 512mb, no more no less.  I don't yet understand how wasm memory works but my impression is it can grow, so I wonder if you could get away with a smaller initial size and allowing growth
- there's a bunch of small functions with names like op_eef9_0_ff but then one of them is enormous, I wonder why

**Comment by mihaip** [comment]
> * emscripten, built with function names included but not debug info, maybe `-g2` or something?

It's using `-O3 -g4` per https://github.com/mihaip/macemu/blob/ff88805eb9a72b22e5346039108e50ec62c5d7cf/BasiliskII/src/Unix/_emenv.sh  (the build system I inherited is autoconf/make plus a bunch of hacks on top, have not had a chance to clean it up)

> * I like how `htons` and `ntohs` are both exported but just point at the same function, never really thought about that before

Interesting, they are distinct functions in the Emscripten libc: https://github.com/emscripten-core/emscripten/blob/4d864df0a57024d667e8db171aab2c3385d04c30/system/lib/libc/musl/src/network/ntohs.c and https://github.com/emscripten-core/emscripten/blob/4d864df0a57024d667e8db171aab2c3385d04c30/system/lib/libc/musl/src/network/htons.c. The optimizer must have noticed they are the same?

> * the memory section seems to request exactly 512mb, no more no less.  I don't yet understand how wasm memory works but my impression is it can grow, so I wonder if you could get away with a smaller initial size and allowing growth

The build flags use `TOTAL_MEMORY=536870912"` (https://github.com/mihaip/macemu/blob/ff88805eb9a72b22e5346039108e50ec62c5d7cf/BasiliskII/src/Unix/_emenv.sh#L7), but the flag was renamed to `INITIAL_MEMORY` at some point, so there's better docs about that. There is an option to allow growth (https://emscripten.org/docs/optimizing/Optimizing-Code.html#memory-growth), but given that the emulated machine has a fixed memory size (of 256MB), the growth mode doesn't seem to be worth it.

> * there's a bunch of small functions with names like op_eef9_0_ff but then one of them is enormous, I wonder why

There's a codegen step to generate all possible 68K CPU instructions. I believe `op_7101_0_ff` corresponds to the the fake `EMUL_OP` opcode implemented by https://github.com/cebix/macemu/blob/4671258ba36cac1a19545b5f666916a30cd91581/BasiliskII/src/emul_op.cpp, which allows a CPU -> host escape hatch (https://github.com/cebix/macemu/blob/4671258ba36cac1a19545b5f666916a30cd91581/BasiliskII/TECH#L187 describes a bit more)
