### ISSUE TITLE
Error: invalid limits flag 3

### ISSUE THREAD

**Issue by kritzikratzi** [evmar/weave#6]
i'm getting the error "invalid limits flag 3"

i attached the wasm file in question.
[edit:delete the file in question as it's something i'm actively working on. i can re-send the file any time]

**Comment by evmar** [comment]
Thanks for trying it out!

What produced this file?  From the spec [the only valid limits flag values are 0 and 1](https://webassembly.github.io/spec/core/binary/types.html#binary-limits), so I'm curious what 3 means in this file.

**Comment by kritzikratzi** [comment]
i'm messing around porting a tiny windows executable to emscripten. i'm not particularly sure what i'm doing, as i'm messing with flags to check what they do. 

i believe this is the gist of the active configuration: 

	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fms-extensions -ffast-math")
	set(CMAKE_CXX_STANDARD 17)
	set(flags "-g4 -g -gsource-map -O3 -pthread -sUSE_SDL=2 -flto -s INITIAL_MEMORY=${mem} -s PTHREAD_POOL_SIZE=5 -fno-rtti -fno-exceptions")
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${flags}")
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${flags}")
	set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS_MINSIZEREL "${flags} -flto -sWASM=1")

sorry that this is so messy. (i _believe_ i was experimenting with getting usable debug symbols).

**Comment by evmar** [comment]
It took some digging, but I found this proposal has this extended serialization:
https://github.com/WebAssembly/threads/blob/main/proposals/threads/Overview.md#spec-changes

**Comment by evmar** [comment]
I pushed a new version of the demo site so you should be able to load your file by drag'n'drop now.
Thanks for trying it out and reporting the bug!
